[package]
name = "raytracer"
version = "0.1.0"
edition = "2024"

[dependencies]
approx = "0.5.1"
rayon = "1.10.0"

[[example]]
name = "projectile"

[[example]]
name = "clock"

[[example]]
name = "circle"

[[example]]
name = "shading"

[[example]]
name = "scene"

[[example]]
name = "plane"
